### ISSUE TITLE
Changing base font size DOES affect grid breakpoints

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites-6#326] opened 2015-11-19 17:47 UTC
The documentation's indicates that, "if you want your base font size to be different and not have it affect the grid breakpoints, set $rem-base to $global-font-size and make sure $global-font-size is a pixel value" (http://foundation.zurb.com/sites-6-docs/global-styles.html#font-sizing). I've done that but it actually does affect the grid sizing.

As you can see from the attached screenshots, I have set $global-font-size to 22px; and $rem-base to $global-font-size. In the attached browser screenshot, you can see that the "small" breakpoint is being applied before hitting the 550px point (the point I defined in my breakpoint variables, also attached).

![screen shot 2015-11-19 at 10 45 44 am](https://cloud.githubusercontent.com/assets/729893/11278901/b72331e2-8eaa-11e5-95d7-95f9ed9198ca.png)
![screen shot 2015-11-19 at 10 42 31 am](https://cloud.githubusercontent.com/assets/729893/11278803/481840c6-8eaa-11e5-9d17-1a962903c1c7.png)
![screen-shot-2015-11-19-at-10 44 27-am](https://cloud.githubusercontent.com/assets/729893/11278871/a0f5e4d2-8eaa-11e5-8659-44b7a891c6af.jpg)

**Comment by gakimball** [comment] 2015-11-19 20:22
Duplicate of zurb/foundation-sites#7021

**Closed by gakimball** 2015-11-19 20:22 UTC
